# Default build parameters.  These may be overridden by local configuration
# settings in build.local.properties.
# loggerLevel can be OFF, DEBUG, TRACE
#

server=localhost
port=26257
secondaryServer1=localhost
secondaryPort1=26258
secondaryServer2=localhost
secondaryPort2=26259
database=test
username=test
password=test
privilegedUser=root
privilegedPassword=
sspiusername=testsspi
preparethreshold=5
loggerLevel=OFF
loggerFile=target/kwjdbc-tests.log
protocolVersion=0
sslpassword=sslpwd
